/* eslint-disable */
/* global WebImporter */

/**
 * Transformer: hoegemeyer site-wide cleanup.
 * All selectors verified against migration-work/cleaned.html.
 *
 * Notes on what is intentionally NOT removed here:
 * - The global header (div.globalheader > header) and footer
 *   (div.globalfooter > footer) are each wrapped in a
 *   .cmp-experiencefragment block, which is mapped as the `fragment` block
 *   in page-templates.json and handled by the fragment parser. Removing them
 *   here would starve that parser, so they are left in place.
 */

const H = { before: 'beforeTransform', after: 'afterTransform' };

export default function transform(hookName, element, payload) {
  if (hookName === H.before) {
    // Auto-generated breadcrumb chrome. In cleaned.html the breadcrumb lives at
    // div.breadcrumb > div.social-share > .social-share-wrapper >
    // .social-share__breadcrumb > div.breadcrumb > nav.cmp-breadcrumb.
    // It is generated by EDS/site shell, not authored, so strip the whole
    // .social-share wrapper before block parsing runs.
    WebImporter.DOMUtils.remove(element, ['.social-share']);
  }

  if (hookName === H.after) {
    // Stray non-authorable elements observed in cleaned.html:
    // <meta> tags emitted inside breadcrumb/image components (e.g. lines 301,
    // 305, 356, 389) and orphaned <source>/<noscript>/<link> markup.
    WebImporter.DOMUtils.remove(element, ['meta', 'source', 'noscript', 'link']);
  }
}
